# Generated by Django 3.2.16 on 2022-10-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='profil_pic',
            field=models.ImageField(blank=True, upload_to='', verbose_name='photo de profil'),
        ),
    ]
